routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('movement.index');
});

Route::resource('activity', 'ActivityController')->except(['create', 'show', 'edit']);
Route::resource('category', 'CategoryController')->except(['create', 'show', 'edit']);
Route::resource('vegetable', 'VegetableController')->except(['create', 'show', 'edit']);
Route::resource('employee', 'EmployeeController')->except(['create', 'show', 'edit']);
Route::resource('movement', 'MovementController')->except(['create', 'show', 'edit']);

Route::get('search', 'MovementController@getSearch')->name('search.index');
Route::post('search', 'MovementController@postSearch')->name('search');

resources/views/activity.blade.php
@extends('layout')

@section('content')
    <!-- Default box -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Crear actividad</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            <button id="new-btn" class="btn btn-info">Nuevo</button>
            <hr/>
            <form id="main-form" method="post" action="{{ route('activity.store') }}">
                {{ csrf_field() }}
                <div class="form-group{{ $errors->has('id') ? ' has-error' : ''}}">
                    <label for="subject">Id Actividad</label>
                    <input id="id-txt" type="text" class="form-control" name="name" disabled="disabled">
                </div>
                <div class="form-group{{ $errors->has('description') ? ' has-error' : ''}}">
                    <label for="type">Descripción</label>
                    <input id="description-txt" type="text" class="form-control" name="description" value="{{ old('description') }}">
                </div>
                <button id="submit" class="btn btn-info btn-block">Enviar</button>
            </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Descripción</th>
                    <th>Acciones</th>
                </tr>
                @foreach($activities as $activity)
                    <tr>
                        <td>{{ $activity->id }}</td>
                        <td>{{ $activity->description }}</td>
                        <td>
                            <a href="" class="btn btn-warning edit" data-toggle="modal" data-target="#answer-modal" data-id="{{ $activity->id }}"><i class="fa fa-sticky-note"></i></a>
                            <a href="" data-id="{{ $activity->id }}" class="btn btn-danger delete"><i class="fa fa-ban"></i></a>
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="3">
                        {{ $activities->links() }}
                    </td>
                </tr>
            </table>
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
@endsection

@section('javascript')
    <script type="text/javascript">
        var url = "{{ route('activity.store') }}";

        $('.delete').on('click', function(evt) {
            if (confirm("Seguro que desea eliminar este tutorial?") ) {
                var id = $(this).data('id');
                var target = this;
                $.ajax({
                    url: url + "/" + id,
                    method: "POST",
                    data: {
                        "_method": "DELETE"
                    },
                    success: function(res) {
                        $(target).parents('tr').fadeOut();
                    },
                    error: function(err) {
                        alert("Ha ocurrido un error, intenta nuevamente");
                    }
                });
            }
            return false;
        });

        $('.edit').on('click', function(evt) {
            var row = $(this).parent().parent().find('td');
            var id = $(row[0]).html();
            $('#id-txt').val(id);
            $('#description-txt').val($(row[1]).html());
            $('#main-form').attr('action', url + "/" + id);
            var method = $('<input>');
            $(method).attr('id', 'method-input');
            $(method).attr('type', 'hidden');
            $(method).attr('name', '_method');
            $(method).val('put');
            $('#main-form').append(method);
        });

        $('#new-btn').on('click', function() {
            $('#method-input').remove();
            $('#main-form').attr('action', url);
            $('#id-txt').val("");
            $('#description-txt').val("");
        });
    </script>
@endsection

resources/views/category.blade.php
@extends('layout')

@section('content')
    <!-- Default box -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Crear categoría</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            <button id="new-btn" class="btn btn-info">Nuevo</button>
            <hr/>
            <form id="main-form" method="post" action="{{ route('category.store') }}">
                {{ csrf_field() }}
                <div class="form-group{{ $errors->has('id') ? ' has-error' : ''}}">
                    <label for="subject">Id Categoría</label>
                    <input id="id-txt" type="text" class="form-control" name="name" disabled="disabled">
                </div>
                <div class="form-group{{ $errors->has('description') ? ' has-error' : ''}}">
                    <label for="type">Descripción</label>
                    <input id="description-txt" type="text" class="form-control" name="description" value="{{ old('description') }}">
                </div>
                <div class="form-group{{ $errors->has('hour_value') ? ' has-error' : ''}}">
                    <label for="type">Valor hora</label>
                    <input id="hour-value-txt" type="text" class="form-control" name="hour_value" value="{{ old('hour_value') }}">
                </div>
                <button id="submit" class="btn btn-info btn-block">Enviar</button>
            </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Descripción</th>
                    <th>Acciones</th>
                </tr>
                @foreach($categories as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->description }}</td>
                        <td>{{ $category->hour_value }}</td>
                        <td>
                            <a href="" class="btn btn-warning edit" data-toggle="modal" data-target="#answer-modal" data-id="{{ $category->id }}"><i class="fa fa-sticky-note"></i></a>
                            <a href="" data-id="{{ $category->id }}" class="btn btn-danger delete"><i class="fa fa-ban"></i></a>
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="3">
                        {{ $categories->links() }}
                    </td>
                </tr>
            </table>
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
@endsection

@section('javascript')
    <script type="text/javascript">
        var url = "{{ route('category.store') }}";

        $('.delete').on('click', function(evt) {
            if (confirm("Seguro que desea eliminar este tutorial?") ) {
                var id = $(this).data('id');
                var target = this;
                $.ajax({
                    url: url + "/" + id,
                    method: "POST",
                    data: {
                        "_method": "DELETE"
                    },
                    success: function(res) {
                        $(target).parents('tr').fadeOut();
                    },
                    error: function(err) {
                        alert("Ha ocurrido un error, intenta nuevamente");
                    }
                });
            }
            return false;
        });

        $('.edit').on('click', function(evt) {
            var row = $(this).parent().parent().find('td');
            var id = $(row[0]).html();
            $('#id-txt').val(id);
            $('#description-txt').val($(row[1]).html());
            $('#hour-value-txt').val($(row[2]).html());
            $('#main-form').attr('action', url + "/" + id);
            var method = $('<input>');
            $(method).attr('id', 'method-input');
            $(method).attr('type', 'hidden');
            $(method).attr('name', '_method');
            $(method).val('put');
            $('#main-form').append(method);
        });

        $('#new-btn').on('click', function() {
            $('#method-input').remove();
            $('#main-form').attr('action', url);
            $('#id-txt').val("");
            $('#description-txt').val("");
            $('#hour-value-txt').val("");
        });
    </script>
@endsection

resources/views/employee.blade.php
@extends('layout')

@section('content')
    <!-- Default box -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Crear empleado</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            <button id="new-btn" class="btn btn-info">Nuevo</button>
            <hr/>
            <form id="main-form" method="post" action="{{ route('employee.store') }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('id') ? ' has-error' : ''}}">
                            <label for="subject">Id Empleado</label>
                            <input id="id-txt" type="text" class="form-control" name="id" disabled="disabled">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('phone') ? ' has-error' : ''}}">
                            <label for="subject">Teléfono</label>
                            <input id="phone-txt" type="text" class="form-control" name="phone" value="{{ old('phone') }}">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : ''}}">
                            <label for="type">Nombre</label>
                            <input id="name-txt" type="text" class="form-control" name="name" value="{{ old('name') }}">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('category_id') ? ' has-error' : ''}}">
                            <label for="type">Categoría</label>
                            <select id="category-cmb" name="category_id" class="form-control">
                            @foreach($categories as $k => $v)
                                <option value="{{ $k }}" @if($k == old('category_id')) selected @endif>{{ $v }}</option>
                            @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('address') ? ' has-error' : ''}}">
                            <label for="type">Dirección</label>
                            <input id="address-txt" type="text" class="form-control" name="address" value="{{ old('address') }}">
                        </div>
                    </div>
                </div>
                <button id="submit" class="btn btn-info btn-block">Enviar</button>
            </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Teléfono</th>
                    <th>Categoría</th>
                    <th>Dirección</th>
                    <th>Acciones</th>
                </tr>
                @foreach($employees as $employee)
                    <tr>
                        <td>{{ $employee->id }}</td>
                        <td>{{ $employee->name }}</td>
                        <td>{{ $employee->phone }}</td>
                        <td data-id="{{ $employee->category->id }}">{{ $employee->category->description }}</td>
                        <td>{{ $employee->address }}</td>
                        <td>
                            <a href="" class="btn btn-warning edit" data-toggle="modal" data-target="#answer-modal" data-id="{{ $employee->id }}"><i class="fa fa-sticky-note"></i></a>
                            <a href="" data-id="{{ $employee->id }}" class="btn btn-danger delete"><i class="fa fa-ban"></i></a>
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="3">
                        {{ $employees->links() }}
                    </td>
                </tr>
            </table>
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
@endsection

@section('javascript')
    <script type="text/javascript">
        var url = "{{ route('employee.store') }}";

        $('.delete').on('click', function(evt) {
            if (confirm("Seguro que desea eliminar este tutorial?") ) {
                var id = $(this).data('id');
                var target = this;
                $.ajax({
                    url: url + "/" + id,
                    method: "POST",
                    data: {
                        "_method": "DELETE"
                    },
                    success: function(res) {
                        $(target).parents('tr').fadeOut();
                    },
                    error: function(err) {
                        alert("Ha ocurrido un error, intenta nuevamente");
                    }
                });
            }
            return false;
        });

        $('.edit').on('click', function(evt) {
            var row = $(this).parent().parent().find('td');
            var id = $(row[0]).html();
            $('#id-txt').val(id);
            $('#name-txt').val($(row[1]).html());
            $('#phone-txt').val($(row[2]).html());
            $('#category-cmb').val($(row[3]).data('id'));
            $('#address-txt').val($(row[4]).html());
            $('#main-form').attr('action', url + "/" + id);
            var method = $('<input>');
            $(method).attr('id', 'method-input');
            $(method).attr('type', 'hidden');
            $(method).attr('name', '_method');
            $(method).val('put');
            $('#main-form').append(method);
        });

        $('#new-btn').on('click', function() {
            $('#method-input').remove();
            $('#main-form').attr('action', url);
            $('#id-txt').val('');
            $('#name-txt').val('');
            $('#phone-txt').val('');
            $('#category-cmb').val('');
            $('#address-txt').val('');
        });
    </script>
@endsection

resources/views/movement.blade.php
@extends('layout')

@section('content')
    <!-- Default box -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Crear movimiento</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            <button id="new-btn" class="btn btn-info">Nuevo</button>
            <hr/>
            <form id="main-form" method="post" action="{{ route('movement.store') }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('id') ? ' has-error' : ''}}">
                            <label for="subject">Id Movimiento</label>
                            <input id="id-txt" type="text" class="form-control" name="id" disabled="disabled">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('activity_id') ? ' has-error' : ''}}">
                            <label for="subject">Actividad</label>
                            <select id="activity-cmb" name="activity_id" class="form-control">
                                @foreach($activities as $k => $v)
                                    <option value="{{ $k }}" @if($k == old('activity_id')) selected @endif>{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('vegetable_id') ? ' has-error' : ''}}">
                            <label for="type">Hortaliza</label>
                            <select id="vegetable-cmb" name="vegetable_id" class="form-control">
                                @foreach($vegetables as $k => $v)
                                    <option value="{{ $k }}" @if($k == old('vegetable_id')) selected @endif>{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('activity_duration') ? ' has-error' : ''}}">
                            <label for="type">Duración actividad</label>
                            <input id="activity_duration-txt" type="text" class="form-control" name="activity_duration" value="{{ old('activity_duration') }}">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('employee_id') ? ' has-error' : ''}}">
                            <label for="type">Empleado</label>
                            <select id="employee-cmb" name="employee_id" class="form-control">
                                @foreach($employees as $k => $v)
                                    <option value="{{ $k }}" @if($k == old('employee_id')) selected @endif>{{ $v }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group{{ $errors->has('activity_date') ? ' has-error' : ''}}">
                            <label for="type">Fecha actividad</label>
                            <input id="activity-date-txt" type="text" class="form-control" name="activity_date" value="{{ old('activity_date') }}">
                        </div>
                    </div>
                </div>
                <button id="submit" class="btn btn-info btn-block">Enviar</button>
            </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Actividad</th>
                    <th>Hortaliza</th>
                    <th>Duración actividad</th>
                    <th>Empleado</th>
                    <th>Fecha actividad</th>
                    <th>Acciones</th>
                </tr>
                @foreach($movements as $movement)
                    <tr>
                        <td>{{ $movement->id }}</td>
                        <td data-id="{{ $movement->activity->id }}">{{ $movement->activity->description }}</td>
                        <td data-id="{{ $movement->vegetable->id }}">{{ $movement->vegetable->description }}</td>
                        <td>{{ $movement->activity_duration }}</td>
                        <td data-id="{{ $movement->employee->id }}">{{ $movement->employee->name }}</td>
                        <td>{{ $movement->activity_date->format('Y-m-d') }}</td>
                        <td>
                            <a href="" class="btn btn-warning edit" data-toggle="modal" data-target="#answer-modal" data-id="{{ $movement->id }}"><i class="fa fa-sticky-note"></i></a>
                            <a href="" data-id="{{ $movement->id }}" class="btn btn-danger delete"><i class="fa fa-ban"></i></a>
                        </td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="3">
                        {{ $movements->links() }}
                    </td>
                </tr>
            </table>
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
@endsection

@section('javascript')
    <script src="{{ asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        //Date picker
        $('#activity-date-txt').datepicker({
            format: 'yyyy-mm-dd',
            language: 'es',
            autoclose: true
        })
        var url = "{{ route('movement.store') }}";

        $('.delete').on('click', function(evt) {
            if (confirm("Seguro que desea eliminar este tutorial?") ) {
                var id = $(this).data('id');
                var target = this;
                $.ajax({
                    url: url + "/" + id,
                    method: "POST",
                    data: {
                        "_method": "DELETE"
                    },
                    success: function(res) {
                        $(target).parents('tr').fadeOut();
                    },
                    error: function(err) {
                        alert("Ha ocurrido un error, intenta nuevamente");
                    }
                });
            }
            return false;
        });

        $('.edit').on('click', function(evt) {
            var row = $(this).parent().parent().find('td');
            var id = $(row[0]).html();
            $('#id-txt').val(id);
            $('#activity-cmb').val($(row[1]).data('id'));
            $('#vegetable-cmb').val($(row[2]).data('id'));
            $('#activity_duration-txt').val($(row[3]).html());
            $('#employee-cmb').val($(row[4]).data('id'));
            $('#activity-date-txt').val($(row[5]).html());
            $('#main-form').attr('action', url + "/" + id);
            var method = $('<input>');
            $(method).attr('id', 'method-input');
            $(method).attr('type', 'hidden');
            $(method).attr('name', '_method');
            $(method).val('put');
            $('#main-form').append(method);
        });

        $('#new-btn').on('click', function() {
            $('#method-input').remove();
            $('#main-form').attr('action', url);
            $('#id-txt').val('');
            $('#activity-cmb').val('');
            $('#vegetable-cmb').val('');
            $('#activity_duration-txt').val('');
            $('#employee-cmb').val('');
            $('#activity-date-txt').val('');
        });
    </script>
@endsection

resources/views/search.blade.php
@extends('layout')

@section('content')
    <!-- Default box -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Buscar movimiento</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            <form id="main-form" method="post" action="{{ route('vegetable.store') }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group{{ $errors->has('id') ? ' has-error' : ''}}">
                            <label for="subject">Hortaliza</label>
                            <input id="id-txt" type="text" class="form-control" name="id">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group{{ $errors->has('harvest_time') ? ' has-error' : ''}}">
                            <label for="subject">Actividad</label>
                            <input id="activity-txt" type="text" class="form-control" name="activity_id">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : ''}}">
                            <label for="type">Empleado</label>
                            <input id="employee-txt" type="text" class="form-control" name="employee_id">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label><input type="radio" name="criteria" value="like"> Contiene...</label>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label><input type="radio" name="criteria" value="starts"> Empiece por...</label>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label><input type="radio" name="criteria" value="ends"> Termine en...</label>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label><input type="radio" name="criteria" value="equals"> Igual a...</label>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <a id="remove-btn" href="" class="btn btn-warning">Quitar filtro</a>
                        <a id="accept-btn" href="" class="btn btn-success">Aceptar</a>
                        <a id="cancel-btn" href="" class="btn btn-danger">Cancelar</a>
                    </div>
                    <div class="col-sm-3">
                </div>
            </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Actividad</th>
                        <th>Hortaliza</th>
                        <th>Duración actividad</th>
                        <th>Empleado</th>
                        <th>Fecha actividad</th>
                    </tr>
                </thead>
                <tbody id="table-body">

                </tbody>
            </table>
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
@endsection

@section('javascript')
    <script type="text/javascript">
        var url = "{{ route('search') }}";

        $('#accept-btn').on('click', function() {
            $.ajax({
                url: url,
                method: 'POST',
                data: {
                    vegetable: $('#id-txt').val(),
                    activity: $('#activity-txt').val(),
                    employee: $('#employee-txt').val(),
                    criteria: $('input[name="criteria"]:checked').val()
                },
                success: function(res) {
                    var elements = ['id','activity','vegetable','activity_duration','employee','activity_date'];
                    $('#table-body').html('');
                    for (var i = 0; i < res.length; i++) {
                        var row = $('<tr>');
                        for (e in elements) {
                            var element = $('<td>');
                            $(element).html(res[i][elements[e]]);
                            $(row).append(element);
                        }
                        $('#table-body').append(row);
                    }
                },
                error: function(err) {
                    alert("Ha ocurrido un error, intenta nuevamente");
                }
            })
            return false;
        });
        $('#remove-btn').on('click', function() {

            $('#id-txt').val(''),
            $('#activity-txt').val(''),
            $('#employee-txt').val(''),
            $('input[name="criteria"]:checked').prop('checked', false);
            return false;
        });
    </script>
@endsection